### ISSUE TITLE
Page wont Load with error

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#338]
Hi Norm 

We can't get this page to load in our local dev environment:
https://arcproject.knack.com/arc-beta#admissions-new/qs--review/queries/6669bd250cca5c0029409611/

Its coming with this error:
KTL.js:12720 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'key')
    at KTL.js:12720:80
    at Array.forEach (<anonymous>)
    at Object.getAllFieldsWithKeywordsInView (KTL.js:12717:46)
    at Object.hideFields (KTL.js:3298:49)
    at HTMLDocument.<anonymous> (KTL.js:14716:28)
    at HTMLDocument.dispatch (k_84cd16df86db786830325e06f7be8b9bee298cd7.js:2:199939)
    at HTMLDocument.s (k_84cd16df86db786830325e06f7be8b9bee298cd7.js:2:195974)
    at Object.trigger (k_84cd16df86db786830325e06f7be8b9bee298cd7.js:2:198508)
    at HTMLDocument.<anonymous> (k_84cd16df86db786830325e06f7be8b9bee298cd7.js:2:206283)
    at Function.each (k_84cd16df86db786830325e06f7be8b9bee298cd7.js:2:176249)
   
I have narrowed it down to this commit: 876f0670ac08aeb161d7fc3a7e4c0ad98d013307

The page loads if I go back to the commit before : b81aff129001f133661e3370c3bbdbc19a21bd8f

Craig

**Comment by cortexrd** [comment]
I've fixed that bug and some more in the next commit.  Please pull Dev and give it a try.

ND

**Comment by CSWinnall** [comment]
Great Thanks
