### ISSUE TITLE
Error with remove connection picker

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#363]
Hi Norm

We are getting this error on multiple apps:

err TypeError: Cannot read properties of null (reading 'connectionPicker')
    at KTL.js:7474:35
    at Array.forEach (<anonymous>)
    at removeConnectionPicker (KTL.js:7472:18)
    at ktlProcessKeywords (KTL.js:6736:17)
    at HTMLDocument.<anonymous> (KTL.js:6481:21)
    at HTMLDocument.dispatch (k_0c7f01687ca49a56d119a7de6c60bb37a9b6e3e5.js:2:199750)
    at HTMLDocument.s (k_0c7f01687ca49a56d119a7de6c60bb37a9b6e3e5.js:2:195785)
    at Object.trigger (k_0c7f01687ca49a56d119a7de6c60bb37a9b6e3e5.js:2:198319)
    at HTMLDocument.<anonymous> (k_0c7f01687ca49a56d119a7de6c60bb37a9b6e3e5.js:2:206094)
    at Function.each (k_0c7f01687ca49a56d119a7de6c60bb37a9b6e3e5.js:2:176060)

Craig

**Comment by cortexrd** [comment]
I can't reproduce it in any page.
Can you?  What view type?

**Comment by CSWinnall** [comment]
That's weird we had the error in 2 apps but now we can't replicate it.  I'll close for now and keep an eye on it.

Craig

**Comment by CSWinnall** [comment]
Hi Norm

I have this error again:
KTL.js:6747 err TypeError: Cannot read properties of null (reading 'connectionPicker')
    at KTL.js:7474:35
    at Array.forEach (<anonymous>)
    at removeConnectionPicker (KTL.js:7472:18)
    at ktlProcessKeywords (KTL.js:6736:17)
    at HTMLDocument.<anonymous> (KTL.js:6481:21)
    at HTMLDocument.dispatch (k_40283f29cfbec3c607fd76000daff689ed00f78a.js:2:199750)
    at HTMLDocument.s (k_40283f29cfbec3c607fd76000daff689ed00f78a.js:2:195785)
    at Object.trigger (k_40283f29cfbec3c607fd76000daff689ed00f78a.js:2:198319)
    at HTMLDocument.<anonymous> (k_40283f29cfbec3c607fd76000daff689ed00f78a.js:2:206094)
    at Function.each (k_40283f29cfbec3c607fd76000daff689ed00f78a.js:2:176060)

And I can replicate it.

Craig

**Comment by CSWinnall** [comment]
I believe the issue is caused by a details view with a field I have added _rcp to. I think it just needs a check for a viewType = form.

This is the field the issue is on:
![image](https://github.com/user-attachments/assets/c5b9940a-1073-4b09-adad-14478d7ea5a6)

**Comment by cortexrd** [comment]
In your case, when the bug appears, why view type is it?

**Comment by CSWinnall** [comment]
A Details View

**Comment by cortexrd** [comment]
Got it now.

**Comment by cortexrd** [comment]
I've pushed the fix in Dev branch.
Can you test it please?

**Comment by CSWinnall** [comment]
Great Thanks
