### ISSUE TITLE
Error for sth on Report views

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#378]
Hi Norm

Getting undefined on reports views neither of which have _sth.

err TypeError: Cannot read properties of undefined (reading '_sth')
    at KTL.js:6882:30
    at KTL.js:6780:21
    at Array.forEach (<anonymous>)
    at KTL.js:6779:29
    at Array.forEach (<anonymous>)
    at iterateViewReports (KTL.js:6778:23)
    at ktlProcessKeywords (KTL.js:6881:17)
    at finalizeSummaryPostProcessing (KTL.js:6623:17)
    at summaryPostProcessing (KTL.js:6606:17)
    at HTMLDocument.<anonymous> (KTL.js:6504:13)

```
iterateViewReports(view, (report, keywords) => {
    keywords._sth && stickyReportTableHeader(report, keywords);
    keywords._stc && stickyReportTableColumns(report, keywords);
    noFilteringInReport(report, keywords);
})
```

Craig

**Comment by cortexrd** [comment]
I also notice that we have two instances of 

`iterateViewReports(view, (report, keywords) => {`

Fixing that now.

**Comment by cortexrd** [comment]
Should be good now.

**Comment by CSWinnall** [comment]
Perfect
