### ISSUE TITLE
Error with number field

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#384]
Hi Norm

I am getting this error on a number field because it doesn't have a format.

![image](https://github.com/user-attachments/assets/23864bc6-2f51-494a-81fd-e320dad3ea45)

KTL-0.28.6.js:1530 Uncaught TypeError: Cannot read properties of undefined (reading 'mark_decimal')
    at Object.extractNumericValue (KTL-0.28.6.js:1530:44)
    at Object.enforceNumeric (KTL-0.28.6.js:2631:66)
    at HTMLDocument.<anonymous> (KTL-0.28.6.js:2343:24)
    at HTMLDocument.dispatch (k_035ba839ee79fc1580af1ff0456be90131c144ea.js:2:199750)
    at HTMLDocument.s (k_035ba839ee79fc1580af1ff0456be90131c144ea.js:2:195785)

Craig

**Comment by CSWinnall** [comment]
Actually I think you have already fixed this in dev

**Comment by CharlesBrunelleIO** [comment]
I can't reproduce. @CSWinnall , is it still an issue?

**Comment by CSWinnall** [comment]
It doesn't cause an issue as such but we do get an error logged. It doesn't cause any problems.

**Comment by CSWinnall** [comment]
There is definitely something going on with this as it also comes up when we create our own input using JS. I'll post the exact conditions when I'm back at work on Tuesday.

**Comment by CSWinnall** [comment]
I can't replicate this now I'll keep an eye out for it.
