### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'click')

### ISSUE THREAD

**Issue by djbbiz** [cortexrd/Knack-Toolkit-Library#84]
I am getting an error in the toolkit browser console:

Uncaught TypeError: Cannot read properties of undefined (reading 'click')
    at Ktl.$.fn.bindFirst (KTL-0.15.0.js:281:49)
    at Object.noInlineEditing (KTL-0.15.0.js:7625:39)
    at HTMLDocument.<anonymous> (KTL-0.15.0.js:10038:23)
    at HTMLDocument.dispatch (k_141f46f4fb861cac18986c2f389f1a59ffad0fad.js:14:29218)
    at HTMLDocument.o (k_141f46f4fb861cac18986c2f389f1a59ffad0fad.js:14:25232)
    at Object.trigger (k_141f46f4fb861cac18986c2f389f1a59ffad0fad.js:14:27768)
    at HTMLDocument.<anonymous> (k_141f46f4fb861cac18986c2f389f1a59ffad0fad.js:14:35575)
    at Function.each (k_141f46f4fb861cac18986c2f389f1a59ffad0fad.js:14:5370)
    at init.each (k_141f46f4fb861cac18986c2f389f1a59ffad0fad.js:14:2085)
    at init.trigger (k_141f46f4fb861cac18986c2f389f1a59ffad0fad.js:14:35550)

The console points to this code:

$.fn.bindFirst = function (name, fn) {
        var elem, handlers, i, _len;
        this.bind(name, fn);
        for (i = 0, _len = this.length; i < _len; i++) {
            elem = this[i];
            handlers = jQuery._data(elem).events[name.split('.')[0]];
            handlers.unshift(handlers.pop());
        }
    };
    //jQuery extensions - END

This part of the code is underlined in red:

[name.split('.')[0]];

I seems to be when a page is first loaded but then it will fix itself when I refresh the URL and reload the page.

Dean

**Comment by cortexrd** [comment]
Investigating this right now.
Thanks for reporting Dean.

Norm

**Comment by cortexrd** [comment]
Dean,

Can you test latest release 0.15.1 please?

Norm

**Comment by djbbiz** [comment]
I have not seen this in awhile so I am going to assume it is fixed
